language: java
jdk:
    - oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_script:
 - "echo $JAVA_OPTIONS"
 - "export JAVA_OPTIONS=-Djava.util.Arrays.useLegacyMergeSort=true"
 - "echo $JAVA_OPTIONS"
script: mvn clean install
